FROM node:18-alpine AS build

WORKDIR /usr/src/app

ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build

# --- Production Stage ---
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]