version: '3.8'

services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: devdash-db-prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - devdash-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend
  backend:
    build:
      context: ./backend
      target: prod 
    container_name: devdash-backend-prod
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy 

  # Frontend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
    container_name: devdash-frontend-prod
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  devdash-data: